os: unstable

environment:
  matrix:
    - nodejs_version: 7

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules -> package.json

matrix:
  fast_finish: true

build: off

version: 1.0.{build}

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn

test_script:
  - node --version
  - yarn package

skip_non_tags: true

deploy:
  provider: GitHub
  auth_token:
    secure: CZ5K7WGDzMAmR+qnbmDtiPCAcjphlh1/zATflHqdp3HM+oFBsiWistS385S15j+5
  artifact: '**\*.Setup.exe'
